### ISSUE TITLE
What is the best way to maintain the configurantion "adapter.xml"

### ISSUE THREAD

**Issue by marciomvm** [adaptris/docker-interlok#6]
Hi,

I created a few examples to use Interlok but I am struggling with how to commit the image with the new configuration. When I finish the commit and run new image the configuration is lost.

I read something about maintaining the configuration in Dockerfile, but still no very clear for me. It's possible to give some tips about the best practice?

Many Thanks,
Marcio Vidal

**Comment by quotidian-ennui** [comment]
There's plenty of options here; the easiest one is to mount the config directory as a docker volume (e.g. something like -> `docker run -it -v -v "/path/to/local/config:/opt/interlok/config"  XXX`) then your config directory is always on your local machine.

Then, you'd probably just have a Dockerfile like this to build your example via docker build

```
FROM adaptris/interlok:3.9.0-zulu-alpine

COPY /path/to/local/config /opt/interlok/config
```
